### ISSUE TITLE
US_5.5: Print and download all AND specific letter of agreements 💰 5

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#118]
**As**
organizer

**I want to**
see, download & print the letter of agreements of the participants

**in order to**
be legally safe.

## Attention
- see #30
- #25 & #26 the letter will be added in profile and listed in event overview

## Acceptance criteria
- The organizer can select accepted user of the event and print their letter of agreements
- The organizer can select all at once and print their letter of agreements
- The organizer can select user of the event and download their letter of agreements
- The organizer can select all at once and download their letter of agreements
- Download one PDF with the letter of agreements

**Tasks**
- [x] Add selection boxes to participants overview
- [x] Add possibility to easily select all participants
- [x] Download letters of agreement for all selected participants (in zip)
- [x] Concatenate all letters of agreement for all selected participants into pdf and download it

**Comment by pinussilvestrus** [comment]
#30 isn't really a dependency here..

**Comment by Baschdl** [comment]
@pinussilvestrus But you can use the print/pdf generation functionality of #30

**Comment by julisa99** [comment]
@MasterCarl was macht du bei der User Story?

**Comment by bjrne** [comment]
Is this merged? Please give a reason when closing issues without commits linked to them.
