### ISSUE TITLE
US_3.1: Accept-All-Button

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#16]
**As** 
organizer

**I want to**
accept all applicants with an Accept-All-Button if the number of participants is not limited

**in order to**
to be faster

**estimation: 8**

## Tasks

- [x] add accept-all-functionality to button
- [x] only organizers see the button
- [x] the button is only visible if there is enough space
- [ ] remove "infinite numer of participants"-functionality to events
- [ ] remove UI button for infinite participants to event creation
- [ ] remove UI button for infinite participants to event editing

## Acceptance criteria

- The not-limited check box is removed from the application creation page. 

- If there are less or equal applicants than maximum number of participants, than the accept all button should be displayed to organizers visiting the overview page. 

- If the number of applicants is larger than the maximum number of participants, than the button should be hidden. 

- Coaches and applicants never see this button.

- When the button is pressed, all applicants for this workshop should be marked as accepted. 

- The accepts are persistent.

**Comment by Baschdl** [comment]
@tobiduer Only if the number of participants is not limited or also if the number of applications is less than the number of possible participants?

**Comment by tobiduer** [comment]
@Baschdl: Than you for the question. The Accept-All-Button should be displayed in both cases. 

As you might already have recognized, this user story also includes the wish to set the maximum number of participants to "not limited" and the UI should reveal this to the user (e.g. with a button next to the input field)

**Comment by tobiduer** [comment]
**Acceptance criteria**

- [ ] If the maximum number of participants for a workshop is not limited (as defined in the workshop edit view), than the accept all button should be displayed to organizers visiting the overview page. 

- [] If there are less or equal applicants than maximum number of participants, than the accept all button should be displayed to organizers visiting the overview page. 

- [] If the number of applicants is larger than the maximum number of participants, than the button should be hided. 

- [] Coaches and pupils do never see this button.

- [] When the button is pressed, all applicants for this workshop should be marked as accepted.

**Comment by tobiasduerschmid** [comment]
As discussed on Slack, removing the not-limited checkbox is part of this user story. (AC's are updated)
