### ISSUE TITLE
US_4.13: "Wie hast du von uns erfahren" Field in Create Profile 💰 5

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#179]
**As**
organiser

**I want**
pupils to enter the "Wie hast du von erfahren" field during create profile

**In order to**
get more data

**Acceptance Criteria:**
- [ ] delete field from application page
- [x] new field in registration
- [x] field is not mandatory
- [x] data is saved in database
- [x] can be modified in profile
- [x] show for organizer the information in the user profile

**Tasks**
- [x] add column to db
- [x] modify form, controller, model
- [x] show for organizer the information in the user profile

**Comment by julisa99** [comment]
forgot to delete the field in application form

**Comment by Fabian-Sommer** [comment]
Why can't this be accepted @tobiduer?
