### ISSUE TITLE
US_3.23: Application Checking Page

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#185]
**As**
applicant

**I want to**
see an overview of my entered data after creating an application

**in order to**
recognize and correct typos or outdated data (e.g. new address) 

# Dependencies
Refs issue #56 

# Tasks
- [x] Headline with information text
- [x] Application data
- [x] Edit Button
- [x] Personal data
- [x] Edit button
- [x] Coaches cannot access
- [x] Redirect to page from application creation
- [x] ability test
- [x] routing test
- [x] vegetarian, vegan
- [x] i18n of dates in locales
- [x] change intro text if deadline is reached
- [x] hide buttons if deadline is reached
- [x] feature test
- [x] redesign info text
- [x] button test if deadline exceeded
- [x] redirect from app edit
- [x] redirect from "my applications">>details
- [x] replace age by birthday

# Acceptance Criteria

- On the top the applicant sees the information that the application can be edited until the deadline and the date of the deadline. 

- When an applicant created an application, he / she sees an application checking page

- In order to edit the application, the user can get to the checking page from the applications overview page (Ref #56)

- the application checking page contains all application data with the title "Meine Bewerbung" and an edit button leading to the edit page of the application.

- the application checking page contains all profile data with the title "Meine Persönlichen Daten" and an edit button leading to the edit page of the profile information. 

- coaches never do see this page (even if they know the URL)

- The birthday is shown instead if the age

# UI
![bewerbung_pruefen](https://cloud.githubusercontent.com/assets/16103359/21154217/d7e20704-c16d-11e6-9b55-a0ad43d01b54.JPG)

**Comment by tobiasduerschmid** [comment]
Customers do not like the "(unwichtig für Auswahl)"
