### ISSUE TITLE
US_1.21: "Anfragen" for Workshops

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#217]
**As** 
user

**I want to** 
be able to make requests through the portal for a workshop with my group, class or something like that. 

**in order to** 
make the process more simple

** 🍪** 

Acceptance Criteria
 - [ ] I have input data fields for 
*Anrede (dropdown, Herr/Frau)
*Vorname und Nachname
*Telefonnummer
*Adresse
*EMail Adresse
*Thema des gewünschten Workshops (2 Wünsche)
Zeitrahmen (plain text field)
Teilnehmeranzahl
Kenntnisstand der Teilnehmer
Freitext zur Anfrage (hint: Anmerkungen)

 - [ ] I have send button

**Tasks:**
- [x] create migrations 🗓 6.1.17
- [x] create validations 🗓 (~6.1.17)
- [ ] create view & tests
