### ISSUE TITLE
US_3.3: Applicants overview

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#23]
**As** 
organizer

**I want to**
have an overview with all applicants (personal data, how often already applied, how often accepted / rejected)

**in order to**
give new rejected applicants a new chance. 

**estimation: 13**
**new estimation: 1**

## Tasks
- [x] Table for Workshop Applicants
- [x] Buttons for other required features
- [x] Add gender and age
- [x] Add number of participation to User 
- [x] Add application_letter details page
- [x] Polish interface design
- [x] Manage visibility options (e.g. not for pupil)

## Acceptance criteria
- **When a user logs into the workshop portal, and selects one workshop, he / she should see this overview page.**
![overview](https://cloud.githubusercontent.com/assets/16103359/20379737/31f754ea-ac9e-11e6-8d28-3c23ac49d4a4.jpg)
See [UI wireframe for overview](https://wireframe.cc/Roqo7E)

- **When the user clicks on "details", the following page is displayed:**
![detail](https://cloud.githubusercontent.com/assets/16103359/20379736/31d8bc56-ac9e-11e6-9e42-d362850ead99.jpg)
See [UI wireframe for details](https://wireframe.cc/86Ceeg)

- **Pupils can not see these two pages.**

- **Coaches and organizers see all applications of the opened workshop.**

- **Data of the current data base state is visualized correctly.**

**Comment by tobiduer** [comment]
See https://wireframe.cc/Roqo7E

**Comment by tobiduer** [comment]
# Overview
![overview](https://cloud.githubusercontent.com/assets/16103359/20379737/31f754ea-ac9e-11e6-8d28-3c23ac49d4a4.jpg)

# Details 
![detail](https://cloud.githubusercontent.com/assets/16103359/20379736/31d8bc56-ac9e-11e6-9e42-d362850ead99.jpg)

**Comment by tobiduer** [comment]
# Details 
![detail](https://cloud.githubusercontent.com/assets/16103359/20379736/31d8bc56-ac9e-11e6-9e42-d362850ead99.jpg)

**Comment by tobiduer** [comment]
Feedback on the current state on (herko)[http://workshop-portal-dev.herokuapp.com]:

- [ ] Please remove the issue numbers and texts in order to provide a good feeling of the view.

- [ ] Please move the back button to the left.

- [ ] Please swap the accept all and print all button positions in order to provide a chronological flow from left to right.

- [ ] Please adjust the theme of red buttons to have a bright text color in order to improve readability.

- [ ] Please do not cut of the text (e.g. "Anzahl der angeno..."). Please break them in two or more lines, if necessary

- [ ] Please show the buttons in one ore more rows with same width in order to have a consistent UI.

**Comment by tobiduer** [comment]
BUG: In the pupils overview, the "Bewerber" should be "Bewerbungen"

**Comment by tobiduer** [comment]
Bewerbungs -> Bewerbungen

**Comment by MasterCarl** [comment]
I noticed you created some tests in events_spec.rb. Would you mind if I moved them into event_spec.rb or renamed them to avoid confusion?

**Comment by ekrebs5** [comment]
You mean whether the feature test should be singular (event_spec.rb) or plural (events_spec.rb), right?
It would be great if the scrum masters @Baschdl could make a convention for this for all teams.

(I am ok with singular, but at the moment we have half singular half plural, so this decision should probably be made for all teams simultaneously)

**Comment by bjrne** [comment]
@ekrebs5 I added  it to my list, we'll discuss it on thursday/friday this week :)
