### ISSUE TITLE
US_3.4: Take notes on applications

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#24]
**As** 
organizer or coach

**I want to**
be able to take notes on applications which other coaches can see

**in order to**
inform about my favorites, experiences with the person

**estimation: 5**

## Tasks
- [x] add notes-field / edit page => ask Tobi
- [x] add notes attribute to application => dependency: Tobi
- [x] show saved notes
- [x] save notes
- [x] ensure access rights (dependency #23)
- [x] make it pretty
- [x] Documentation
- [x] alles auf deutsch
- [x] feature test

## Acceptance criteria

- When a coach or an organizer visit the details page, he / she can add a textual note to application that should be displayed on the details page. Notes are visible to coaches and organizers. 

- These notes should never be visible to the applicants. 

- Notes are persistent.

**Comment by tobiduer** [comment]
Additional details:
These notes should NOT be visible to the pupils!

**Comment by frederike-ramin** [comment]
@tobiduer in the page overview of a user (in corresponding EPIC) there is a button for "Notiz hinzufügen". We talked about it as if there was supposed to be just one note, that can be edited. What is the case?

**Comment by tobiduer** [comment]
@frederike-ramin: This was a misunderstanding. Please allow multiple notes in order to allow many coaches to add notes. 
Furthermore, notes can be edited and removed by the author and organizers only.

**Comment by frederike-ramin** [comment]
@tobiduer This is a lot different from what we expected and estimated. It wasn't mentioned that we should also edit and delete notes. I suggest that we turn that into another User Story as it would make things a lot more complicated.

**Comment by tobiduer** [comment]
@frederike-ramin: Ok. I will create a new user story for this. The team can decide on whether to make it in this sprint or the next.
