### ISSUE TITLE
US_3.25: Application canceled state

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#242]
**As**
organizer

**I want to**
change participants application state to canceled

**in order to**
be able to choose an alternative applicant who was rejected. 

# Tasks

## New state:
- [x] new canceled + pre_accepted state
- [x] refactor code accordingly
- [x] add pre_accepted application_letter factory
- [x] rewrite (accepted/rejected)_applications_count

- [x] rename Event accept_all_application_letters
- [x] update accepted_application_count to use both accepted states
- [x] rename application_letter_applicant_gongakrobatic_accepted
- [x] make sure, that you can filter after all statuses (pretty much refactor everything in that test) features/events_spec filter displayed application_letters
- [x] has as many participants as accepted applications
- [x] click on accept radio button --> pre_accept
- [x] checks states of applications
- [x] coaches see pre_accepted status
- [x] make only accepted, rejected, pending and alternative selectable, not cancled and pre_accepted
- [ ] pre_accepted -> accepted
- [x] rename draft status to acceptance and rejection
- [ ] test states
- [x] selectable_statuses as Application_letter variable

## Actually do stuff:
- [x] cancel button for accepted applications
- [x] cancel when clicked
- [x] make accept button appear (alternatives)
- [x] only accept button when counter good (alternatives)
- [x] pre_accept, when clicked (alternatives)
- [ ] make accept button appear (rejected)
- [ ] only accept button when counter good (rejected)
- [ ] pre_accept, when clicked (rejected)
- [ ] make email button appear (pre_accepted)
- [x] ASK PO TO SEND ALL EMAILS INSTEAD OF LETTER ICON
- [x] ASK PO IF ONLY RECIPIENTS OF EMAIL SHOULD FINALLY BE ACCEPTED
- [ ] redirect to mail sending acceptance email when clicked
- [ ] accept ONLY recipients of email after mail button clicked
# Acceptance criteria

- When the event is in state execution, organizers should see a button "cancel" in the row of each accepted participant. 

- When the organizer pushed the button, then the application is canceled, meaning that the applicant will not participate in the event (similar to rejected) 

- After pushing the cancel button, the organizer can choose a new participant out of the list of alternatives (Nachrücker) and if no alternatives present, then a list of rejected applicants. 

- Applicants who have been accepted in the execution state but did not get an email yet have an emal icon next to the "angenommen" label that lead to the page for sending the acceptance email to him / her. 

- After discussion with PO: The new pre_accepted state leads (on the application_letters index page) to a status display of either "pending" (if before deadline) or "In Beabeitung" (if after deadline)

See Epic_3.3: Application States (Refs #233)

# UI
## Event is in execution state. 
![folie1](https://cloud.githubusercontent.com/assets/16103359/21817499/7fc49d2c-d764-11e6-847c-c5daf80427f2.JPG)

## After pushing one "abgesagt" button: "Nachrücker" can be accepted.
![folie2](https://cloud.githubusercontent.com/assets/16103359/21817498/7fc16fbc-d764-11e6-95a4-a771464fed1a.JPG)

## After pushing the "annehmen" button
![folie3](https://cloud.githubusercontent.com/assets/16103359/21817501/7fc60842-d764-11e6-89e1-4e053727f485.JPG)

## After pushing one other "abgesagt button": rejected applicants can be accepted
![folie4](https://cloud.githubusercontent.com/assets/16103359/21817500/7fc60054-d764-11e6-9e12-4513f904a9f6.JPG)

[As one pdf file](https://github.com/hpi-swt2/workshop-portal/files/696886/Nachrucker.pdf)

**Comment by tobiasduerschmid** [comment]
The button "Abgesagt" should be  renamed to "Absagen"
