### ISSUE TITLE
US_3.27: UI for event states

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#244]
**As**
user of the portal

**I want to**
see exactly the UI elements applicable for the current state of the event

**in order to**
avoid errors and confusion

# Tasks

- [x] no apply buttons after application deadline

- [x] show application button

- [x] replace apply button with show application button after applying

- [x] radio buttons are viewable dependent on state (only in selection, or with what issue #242 does)

- [x] buttons for print all, accept all, sending emails and printing badges and viewing the participant list are viewable dependent on state

# Acceptance criteria

## Application phase

- When the deadline is over, no "Bewerben" buttons should be displayed (on any page!)

- When a user applied for an event the "Bewerben" buttons should be replace with "Bewerbung anzeigen" and link to the application checking page. (Refs #185)  

- When the the event is in the application state, then the selection of participants should not be possible.

- When the the event is in the application state, then there are not button for print all, accept all, sending emails and printing badges and viewing the participant list should be invisible. 

## Selection phase

- When the event is in the selection state, then the selection of participants should be possible (set application state to accepted, rejected, alternative but NOT to canceled)

- When the the event is in the selection state, then organizers can view the buttons for: print all, accept all, sending emails and but not for: printing badges and viewing the participant 

## Execution phase

- When the event is in the execution state, then organizers can view the buttons for: printing badges and viewing the participant but not for: print all, accept all, sending acceptance / rejection emails (expectation: Refs #243)
 
See Epic_3.3: Application States (Refs #233)

**Comment by tobiduer** [comment]
@bjrne: Thank you :) I adjusted the US.

**Comment by tobiasduerschmid** [comment]
is enhances by Refs #418
