### ISSUE TITLE
US_4.1: Letter of agreement 💰13

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#25]
**As**
pupil

**I have to**
upload a letter of agreement signed by my parents  (if age < 18)

**in order**
to participate in the camp.

**Acceptance Criteria**
- "Durchsuchen" Feature
- Upload button
- Information: Only *pdf
- An error will be displayed if the upload is not *pdf
- Support of pdf size up to 300MB (else error message)
- You can see the date and the time of the upload

**Tasks**
- [x] create temporary user profile page
- [x] create form for upload
- [x] limit uploads to PDF format and 300 MB size
- [x] create db table "agreement_letters"
- [x] save uploaded files in filesystem
- [x] replace old file if new file is uploaded
- [x] show upload time stamp if file was already uploaded
- [x] hide upload form from 18+ users

**Comment by tobiduer** [comment]
Dependency: Role Pupil, Role Organizer, Entity Application
