### ISSUE TITLE
US_4.2: Check letter of agreement 💰 3

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#26]
**As**
organizer

**I want to**
check whether all participants in an event have uploaded the letters of agreement (if age < 18)

**in order to**
automate this process. 

**Acceptance Criteria**
- Show symbol in participants overview 
  - green: letter is there
  - grey: >=18
  - red: missing
- sort by missing letter of agreement
- While holding the mouse on the symbol, you can see the date and the time of the upload

**Tasks**
- [x] add participants overview
- [x] fill in appropriate color for each participant
- [x] sort by missing letter of agreement
- [x] tool tip on mouse hover

**Comment by tobiduer** [comment]
Dependency: US_4.1(#25)
