### ISSUE TITLE
US_3.6: Counter

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#29]
**As** 
organizer

**I want to**
see a counter how many applicants have already been accepted and how many free places are left for the event.

**in order to**
have an overview how many pupils we can accept.

**estimation: 8**

## Tasks

- [x] add text for counter
- [x] compute and show free places
- [x] compute and show occupied places
- [ ] update if changed (accept/reject)
- [x] ensure access rights (dependency: #23)
- [x] only subtract accepted applications (dependency: #45)
- [x] Documentation
- [x] alles auf deutsch

## Acceptance criteria

- When an organizer or coach visits the overview page, the counter should display the number of free places in the workshop. 

- When an organizer accepts a new applicant, the counter should be updated **immediately** for all sessions.  

- (Applicants never see this counter.)

**Comment by tobiduer** [comment]
**Acceptance criteria**
When an organizer or coach visit the overview website, the counter should display the number of free places in the workshop. When an organizer clicks accepts a new applicant, the counter should be updated immediately for all sessions.

**Comment by aloeser** [comment]
@tobiduer should we show only the number of free places or also how many have been accepted yet?

**Comment by tobiduer** [comment]
@aloeser: Please show both.
