### ISSUE TITLE
US_4.6: Print all applications at once 💰 13

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#30]
**As** 
organizer

**I want to**
have a button with which I can print out all applications for an event at once

**in order to**
be faster

## Attention
Please ensure, that one application is printed on one page and an overview page is printed as well.
Generating a pdf that can be downloaded would be enough if opening a printing dialog would involve more implementation effort.
Maybe similar to #34 .

## Acceptance criteria

- When a coach or an organizer visit the overview page, the print all button should be displayed. 

- When the button is pushed, a pdf is generated and can be downloaded by the user (not persistent) 

- The pdf contains the content of the overview page without the buttons. 

- The pdf contains the content of all applications for this workshop from the details page without the buttons.

- One detail page in the pdf file contains only one applications. 

- If applications are too large for one page, page numbers are printed in a footer. 

- A header with the name of the applicant and the name of the workshop is printed on each detail pdf page. 

- The layout of the pdf print is optimized for DIN A4 pages.

## Tasks
- [x] add "print" button to applicants overview
- [x] generate an empty pdf
- [x] download the pdf when the button is pressed
- [x] add empty overview page to pdf
- [x] add table with the application overview data to overview page
- [x] add one application page for each applicant
- [x] add information from the application detail page to application page
- [x] add motivation letter to application page
- [x] add header to application page
- [x] add footer to application page
- [x] add cans
- [x] add translations
- [x] make everything pretty

**Comment by tobiduer** [comment]
Additional details: 
Please ensure, that one application is printed on one page and an overview page is printed as well. 
Generating a pdf that can be downloaded would be enough if opening a printing dialog would involve more implementation effort.

**Comment by Baschdl** [comment]
How should the one page limitation be implemented if a pupil writes a long cover letter which doesn't fit on one page? Cut off the text?...

**Comment by tobiduer** [comment]
@Baschdl: Please print two pages with page numbers and the same header in this case. Cutting off the text is not an option.

**Comment by tobiduer** [comment]
**Acceptance criteria**

- [ ] When a coach or an organizer visit the overview page, the print all button should be displayed. 

- [ ] When the button is pushed, a pdf is generated and can be downloaded by the user (not stored in the database) 

- [ ] The pdf contains the content of the overview page without the buttons. 

- [ ] The pdf contains the contend of all applications for this workshop from the details page without the buttons.

- [ ] One detail page in the pdf file contains only one applications. 

- [ ] If applications are too large for one page, page numbers are printed in a footer. 

- [] A header with the name of the applicant and the name of the workshop is printed on each detail pdf page.

**Comment by Baschdl** [comment]
Similar to #34

**Comment by tobiasduerschmid** [comment]
Please remove the address from the
