### ISSUE TITLE
US_5.1: Generate name badge 💰 13

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#33]
**As** 
organizer

**I want to**
be able to generate name sign on one click

**in order to**
be faster

**Attention**
Button for generate the name badges should be on the participants page not on the application page.

**Acceptance Criteria**
- select all or select only a few
- after selecting: button for printing/generate pdf
- generate a pdf
- features for:
  - logo at the top
  - name in the middle (show both as option: first name and/or last name
  - bei Externen (bspw Dschool) auch Organisationsname unter den Namen setzen
  - area at the bottom for a color
- every feature is changeable (different colors, another logo, only first name, ...)
![example](https://scontent.xx.fbcdn.net/v/t1.0-9/527902_419783841392579_1238369441_n.jpg?oh=917384edee2a581467ea107afe0d0af8&oe=58CCFEF9)

**Tasks**
- [x] refactor into own class
- [x] upload for logo
- [x] drop down for first name/full name
- [x] check box for organisation name
- [x] check box for colored rectangle
- [x] render logo
- [x] render first name/full name accordingly
- [x] render organisation name
- [x] render group color
- [x] make the badges super pretty
- [x] validate uploaded logo as jpg or png
- [ ] make the UI super pretty
- [ ] move button to the participants page
- [x] test
- [x] I18n
- [ ] document

**Comment by julisa99** [comment]
**depencies:**  role organizer

**Comment by pinussilvestrus** [comment]
For this sprint: Plain pdf with name

**Comment by radscheit** [comment]
@julisa99 

1. Measurements of print sheet?
2. Measurements badge?
3. Is there a ISO number for the used print sheet?

**Comment by julisa99** [comment]
[Namensschilder_Standard.DOCX](https://github.com/hpi-swt2/workshop-portal/files/598456/Namensschilder_Standard.DOCX)

**Comment by pinussilvestrus** [comment]
Refactoring of #43 : Move PDF Generation to own class

**Comment by julisa99** [comment]
Hey, ich erhalte immer eine Fehlermeldung beim ersten Erstellen von den Namensschildern im aktuellen Master. Woran liegt das?
