### ISSUE TITLE
US_5.3: Upload materials 💰 5

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#36]
**As** 
organizer and coach

**I want to**
be able to provide materials

**in order to**
all participants get materials 

## Attention
- later sort the material, see #60 

## Acceptance Criteria
- show in event a material area
- add material upload button: If the upload button is pressed, you can add _pdfs_, _ppt / pptx_, _doc / docx_, _excel-format_, _zip-file_, essential code file formats (java, c #, c ++, c), pictures (png, jpg, bmp, gif) and videos (wmv, mpg4, avi, mov).

## Tasks
- [x] show a material area on the event-page
- [x] show a upload button on the event-page
- [x] add material-property to event-model as string of material-directory in ~/storage/materials
- [x] show every file in material-directory in material area (at least filename and filetype)
- [x] If the upload button is pressed, you can add any files
- [x] restrict view of material area and upload button to organizer and coach

**Comment by julisa99** [comment]
**depencies:** role organizer
