### ISSUE TITLE
US_3.10: Create email drafts for acceptance and rejection

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#39]
**As** 
organizer 

**I want to**
define emails for acceptance and rejection as drafts. 

**in order to**
load them later.

old estimation: 100
**estimation: 8**

## Tasks
- [x] Add "save as draft" button according to #57 
- [x] Create Email_Template table
- [x] Define action for creating new Email (only subject + content) with fitting label

## Acceptance criteria

- When an organizer pressed one of the email buttons on the overview page and the dialog is opened, the organizer **can add a new draft as template** to be stored in the database for new workshops. 

- Acceptance and rejection should be mapped by the system. This means, when the send-accept-mails-button on overview page was pressed, drafts for acceptance should be saved and not for rejection and vice versa. 
- Drafts have a subject for the email and the email content. 

- Drafts are persistent. 

Please discuss your solution ideas with Lisa Ihdes team. (US_4.4, Refs #38)

**Comment by tobiduer** [comment]
Similar to US_4.3 (Refs #35)

**Comment by tobiduer** [comment]
Additional details: 
In order to simplify finding old drafts, the user should be able to define labels for the corresponding events and the subject of the email. 

Please discuss your solution ideas with Lisa Ihdes team.

**Comment by tobiduer** [comment]
**Acceptance criteria**

- [ ] When an organizer pressed one of the email buttons on the overview page and the dialog is opened, email drafts for acceptance / rejection can be chosen as templates and copied to clipboard.

- [ ] When an organizer pressed one of the email buttons on the overview page and the dialog is opened, the organizer can add a new draft as template to be stored in the database for new workshops. 

- [ ] Acceptance and rejection should be mapped by the system. This means, when the accept mail button was pressed, drafts for acceptance should be displayed / save and not for rejection and vice versa.

**Comment by tobiduer** [comment]
Belongs to Epic_3.2: Emails (Refs #57)
