### ISSUE TITLE
US_5.1a: Generate plain name badge 💰 5

### ISSUE THREAD

**Issue by pinussilvestrus** [hpi-swt2/workshop-portal#43]
**As**
organizer

**I want to**
be able to generate a plain name sign on one click

**in order to**
be faster

**Acceptance Criteria**
- select all or select only a few
- after selecting: button for printing/generate pdf
- generate a pdf with plain name sheets with 10 on one site, dinA4

**Tasks**
- [x] create "print name badges" button on applications overview pages (estimation: 1) refs #23
- [x] create "print badges" page with a list of all participants (estimation: 1)
- [x] make list of participants selectable in order to choose all or only a few (estimation: 3) refs #45
- [x] create print button/generate pdf button on print page (estimation: 1)
- [x] create pdf generation functionality (estimation: 5)
- [x] make pdf rendering more dynamically (estimation: 2)

**Comment by pinussilvestrus** [comment]
refs #45

**Comment by pinussilvestrus** [comment]
- [ ] create "print name badges" button on applications overview pages (estimation: 1)
- [ ] create "print badges" page with a list of all participants (estimation: 1)
- [ ] make list of participants selectable in order to choose all or only a few (estimation: 2)
- [ ] create print button/generate pdf button on print page (estimation: 1)
- [ ] create pdf generation functionality (estimation: 8)
