### ISSUE TITLE
US_3.11: Mark as accepted / rejected

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#45]
**As**
organizer

**I want to**
mark applications as accepted or rejected before sending the emails

**in order to**
change my decision before I am absolutely sure. 

**estimation: 8**
**new estimation: 3**

## Tasks
- [x] add radio buttons to the overview page
- [x] add update mechanism for status state
- [x] ensure access rights and display the state as text if no change can be made
- [x] documentation / tests
- [x] when button for sending email was pushed, the radio button is not visible any more

## Acceptance criteria
- When an organizer clicks on the radio button "annehmen" / "ablehnen" on the overview page or details page, the application should be marked as accepted / rejected. This should be displayed in both pages.

- When an organizer visits the overview page, he / she sees a three-state-radio button accept / reject / no decision yet. 

- When the decision is made (pushed button for sending email), the radio button is not visible any more. in order to deny any changes.   

- Coaches and applicants do not see this button but the text of the current state

- The accept and reject is persisted.

## Feedback

- I can not accept / reject applications of other pupils.

**Comment by tobiduer** [comment]
**Acceptance criteria**
When an organizer clicks on the button "annehmen" / "ablehnen"in the overview or details view, the application should be marked as accepted / rejected. This should be displayed in both views.

**Comment by tobiduer** [comment]
Functionality worked on Alex' laptop. I am happy :)

**Comment by TimBasel** [comment]
The PR #183 currently not completes the US.
It is currently possible to change the status of an application even after the email is send. This should not be possible, after the Acceptance Criteria of the US.

**Comment by tobiduer** [comment]
@TimBasel: Thank you for your comment! This is a serious problem. 

@ekrebs5 @querenker: When you fix this, please keep in mind, that we want to change the status of "Nachrücker" to "angenommen", if someone cancels his / her acceptance (e.g. because of exams). Therefore your implementation should re extensible in this direction. Probably we would add a status "canceled" in the future for accepted applicants that will not participate in the event that only changed from "angenommen" to "wiederrufen" or something like this. This is NOT part of this US but maybe could be implemented easier if you keep it in mind.
