### ISSUE TITLE
US_4.15: Unpublish  button & show status 💰 5

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#49]
**As**
organizer

**I want to**
have an unpublish button and status label for events

**In order to**
manage them better

**Acceptance Criteria:**
[ ] unpublish/publish switch on "event edit"-page & "create event"-page which doesn't delete the event but removes the event from the public/unpublic list of events
[ ] show status of event (publish, unpublish) for organizer

![rastergrafik](https://cloud.githubusercontent.com/assets/8758907/21842628/f6cfa9a6-d7e7-11e6-8802-ffe31c4340be.png)

Label:
<img width="76" alt="label" src="https://cloud.githubusercontent.com/assets/8758907/21842633/fa73be76-d7e7-11e6-92f4-cb274040e972.PNG">

**Tasks**
- [x] add published field to database
- [x] add button to form
- [x] organizers can see event status
- [x] pupils can only see published events
- [x] unify with old draft functionality
