### ISSUE TITLE
Epic_3.2: Emails

### ISSUE THREAD

**Issue by tobiduer** [hpi-swt2/workshop-portal#57]
# Contained User Stories

- [x] US_3.10: Create email drafts (Refs #39)

- [x] US_3.13: Load email drafts (Refs #53)

- [x] US_3.14: Send emails (Refs #55)

# Activities
![activit_emaily jpg](https://cloud.githubusercontent.com/assets/16103359/20541512/e7b0713c-b0fd-11e6-887b-b3b99756bf10.png)

# Roles / Privileges
![usecases_email jpg](https://cloud.githubusercontent.com/assets/16103359/20541514/e7bc66cc-b0fd-11e6-83b0-8832143e39ad.png)

# UI Sketch
![e-mails](https://cloud.githubusercontent.com/assets/16103359/20541591/3dd01ee6-b0fe-11e6-99fe-10a1023cd0e0.png)
![As PDF](https://github.com/hpi-swt2/workshop-portal/files/607559/E-Mails.pdf)

**Comment by tobiduer** [comment]
[E-Mails.pdf](https://github.com/hpi-swt2/workshop-portal/files/607503/E-Mails.pdf)

**Comment by tobiasduerschmid** [comment]
Lable email drafts (Refs #54) was removed because of low priority and less development time.
