### ISSUE TITLE
US_5.4: Add Can's for every role 💰 5

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#59]
**As**
coach, organizer and pupil

**I want to have**
only access to my area and my functions

**in order to**
get a 403 error site or have no visible buttons 

**Attention:**
  - As user I can switch to a role in a dropdown by registration (#51)

**Acceptance Criteria**
____
  - As **coach** I can: no USs for Coach in our Sprint1
  
____
  - As **organizer** I can:
    - create name badges by:
      - select all or select only a few participants
      - after selecting: button for printing/generate pdf    

    - see on the event page the participants of the event and their allergies/eating information by:
      - hide and acitivate(if: show vegan, vegetarian and allergies symbol) the allergies and eating information
      - sort by eating habits groups (vegan, vegetarian and none) XOR show allergies at the top
      - show allergies information: While holding the mouse on the symbol, you can see more information.
      - option for printing/generate pdf

  - Check letter of agreement by showing symbol in participants overview 
    - green: letter is there
    - grey: >=18
    - red: missing
  - sort by missing letter of agreement
  - While holding the mouse on the symbol, you can see the date and the time of the upload

  - Generate email-lists of participants or groups:
    - Show me an event overview with button to generate an email-list with all participants or some groups (only team blue, etc.)
_____
  - As **pupil** I can:
    - add a letter of agreement:
      - with a "Durchsuchen" option with an upload button
      - can see the date and the time of the upload

**Tasks**
- [x] US 4.1 (pupil, upload letter)
- [x] US 4.2 (organizer, view participants)
- [x] US 4.3 (organizer, email list)
- [x] US 4.5 (organizer, see eating habits)
- [x] US 5.1a (organizer, name badge)

**Comment by pinussilvestrus** [comment]
refs https://github.com/hpi-swt2/workshop-portal/pull/51

**Comment by radscheit** [comment]
- [ ] Expand user model
- [ ] Define role rights

**Comment by radscheit** [comment]
@julisa99 Please explain the last two points of he user story.

**Comment by radscheit** [comment]
@julisa99 Please define the organizer functions?
